version: '3'
services:
  mysql-docker-container:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: wacad010
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./dados:/var/lib/mysql